ERROR    util_tools.logs_util.recordlog:connectMysql.py:26 连接数据库失败，(2003, "Can't connect to MySQL server on 'localhost' ([WinError 10061] 由于目标计算机积极拒绝，无法连接。)")
INFO     util_tools.logs_util.recordlog:conftest.py:12 -------测试用例开始执行-------
INFO     util_tools.logs_util.recordlog:basePage.py:68 打开页面：https://www.leafground.com/file.xhtml
INFO     util_tools.logs_util.recordlog:basePage.py:161 找到元素：xpath = //*[@id="j_idt88:j_idt89_input"]
INFO     util_tools.logs_util.recordlog:basePage.py:235 元素被输入内容：('xpath', '//*[@id="j_idt88:j_idt89_input"]')，输入的内容为：C:\Users\yaozm\Desktop\文件上传.txt
INFO     util_tools.logs_util.recordlog:basePage.py:161 找到元素：xpath = //*[@id="j_idt88:j_idt89"]/span[2]
INFO     util_tools.logs_util.recordlog:basePage.py:79 获取标签文本内容：文件上传.txt 5 Bytes
INFO     util_tools.logs_util.recordlog:conftest.py:14 -------测试用例执行完毕-------
INFO     util_tools.logs_util.recordlog:conftest.py:16 正在清理测试数据...
ERROR    util_tools.logs_util.recordlog:connectMysql.py:65 删除数据库数据出现异常，'ConnectMysql' object has no attribute 'cursor'